#!/usr/bin/env python3

import sys
import os

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_ansi_art_file> <output_d_file>")
        sys.exit(1)

    input_file_path = sys.argv[1]
    output_file_path = sys.argv[2]

    try:
        with open(input_file_path, 'r', encoding='utf-8') as f_in:
            ansi_content = f_in.read()
    except FileNotFoundError:
        print(f"Error: Input file '{input_file_path}' not found.")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading input file '{input_file_path}': {e}")
        sys.exit(1)

    # Determine module name from output path (e.g., kernel/ansi_art.d -> kernel.ansi_art)
    module_name = os.path.splitext(output_file_path.replace('/', '.'))[0]

    d_source_content = f"""// This file is auto-generated by ans_to_d.py
module {module_name};

public immutable string ansiArtData = q"EOF\n{ansi_content.strip()}\nEOF";
"""

    with open(output_file_path, 'w', encoding='utf-8') as f_out:
        f_out.write(d_source_content)
    print(f"Generated D source file: {output_file_path}")

if __name__ == "__main__":
    main()
