// This file is auto-generated by ans_to_d.py
module kernel.ansi_art;

public immutable string ansiArtData = q{
ESC[1;31mHello from ANSI Art!ESC[0m
ESC[1;34mBlue TextESC[0m
ESC[HESC[2JThis will clear screen and go to top.
};
