// This file is auto-generated by ans_to_d.py
module kernel.utils.plymouth_logo;

public immutable string ansiArtData = q"EOF
ESC[1;34m
 ____  _                    _                        ____  ____
|  _ \| |__   ___  _ __ ___| |_ ___  _ __ ___  ___  |  _ \|  _ \
| |_) | '_ \ / _ \| '__/ _ \ __/ _ \| '__/ _ \/ __| | |_) | | | |
|  __/| | | | (_) | | |  __/ || (_) | | |  __/\__ \ |  __/| |_| |
|_|   |_| |_|\___/|_|  \___|\__\___/|_|  \___||___/ |_|   |____/
ESC[0m
EOF";
